---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ivmjlfeq/public_html/
    - /bin/cp *.php $DEPLOYPATH
    - /bin/cp *.css $DEPLOYPATH
    - /bin/cp *.js $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH